language: node_js

cache:
  yarn: true

jobs:
  include:
    - name: client
      node_js:
        - "10"
      script:
        - cd client
        - yarn install --pure-lockfile --prefer-offline
        - yarn test
        - yarn build
    - name: server
      node_js:
        - "10"
      script:
        - cd server
        - yarn install --pure-lockfile --prefer-offline
        - yarn build
        - yarn test

install: skip

branches:
  only:
    - master

# This approach only works when all modules use the same script commands
# env:
#   - DIR=client
#   - DIR=server
#
# script:
#   - cd $DIR
#   - yarn install --pure-lockfile --prefer-offline
#   - yarn build
#   - yarn test
#
# install: skip
#
# branches:
#   only:
#     - master
